FROM sharededitor/base as builder

RUN apt-get update && \
  apt-get install -y build-essential cmake && \
  rm -rf /var/lib/apt/lists/*

COPY . .
RUN ./scripts/build_stubClient.sh



FROM sharededitor/base

RUN useradd -ms /bin/bash user
COPY --from=builder /app/bin/stubClient /app/bin/stubClient
USER user

ENTRYPOINT ["/app/bin/stubClient"]
