name: Base

on:
  schedule:
    # this will run at 3 AM the 1st for each month
    - cron: '0 3 1 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@0.0.1
      - name: Set the commit to build
        run: |
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
             echo "::set-env name=commit_ref::${{ github.event.pull_request.head.sha }}"
          else
             echo "::set-env name=commit_ref::${{ github.sha }}"
          fi
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: "${{ env.commit_ref }}"
      - name: Build base image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sharededitor/base
          username: ${{ secrets.DOCKER_USERNAME }}
          dockerfile: docker/Dockerfile_base
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.commit_ref }}"
        if: github.ref == 'refs/heads/master'
      - name: Build base image (CI)
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sharededitor/base
          username: ${{ secrets.DOCKER_USERNAME }}
          dockerfile: docker/Dockerfile_base
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "${{ env.commit_ref }}"
        if: github.ref != 'refs/heads/master'
