name: Server

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    # this will run at 4 AM the 1st for each month
    - cron: '0 4 1 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@0.0.1
      - name: Set the commit to build
        run: |
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
             echo "name=commit_ref::${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          else
             echo "name=commit_ref::${{ github.sha }}" >> $GITHUB_ENV
          fi
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: "${{ env.commit_ref }}"
      - name: Build server image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sharededitor/server
          username: ${{ secrets.DOCKER_USERNAME }}
          dockerfile: docker/Dockerfile_server
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.commit_ref }}"
        if: github.ref == 'refs/heads/master'
      - name: Build server image (CI)
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sharededitor/server
          username: ${{ secrets.DOCKER_USERNAME }}
          dockerfile: docker/Dockerfile_server
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "${{ env.commit_ref }}"
        if: github.ref != 'refs/heads/master'
